### ISSUE TITLE
执行build.py时出现错误

### ISSUE THREAD

**Issue by gene-2012** [upizpp/PhiScript#1]
```bash
  File "build.py", line 15, in <module>
    def main(args: list[str]) -> None:
TypeError: 'type' object is not subscriptable
```

**Comment by upizpp** [comment]
这是python3.9对类型标注新增加的Feature，3.9以下的版本运行会报错，
更新python的版本到3.9以上或者删掉build.py文件中类似于list[xxx]的代码即可。
 [What's New In Python 3.9](https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections)
