### ISSUE TITLE
关于修改文件名称

### ISSUE THREAD

**Issue by gene-2012** [upizpp/PhiScript#5]
在[pr#4](https://github.com/upizpp/PhiScript/pull/4)中，我提交的文档出现了拼写错误，应为SYNTAX_DOC.md，希望可以对我的所有提交进行review。

**Comment by upizpp** [comment]
抱歉，我没有注意到它，现已修改。
https://github.com/upizpp/PhiScript/commit/469249ae1b6fe67cec0b4bf314a00d31276cb032
